console.log("that was well brought up, too bad you weren't");
console.log("Does a duck with a boner drag weeds?");
console.log(" it was a sick ostrish");
console.log("allegedly");
console.log("You're made of spare parts, aren't ya bud?");
console.log("And i suggest you let that one marinate.");
console.log("Oh, get off the cross, we need the wood.");
console.log("it's SUSHIS AND SUSHEMI'S");
console.log("We've only got one shot at this. One chance. One win. You know? vomit on your mom's spaghetti, or whatever that talking singer says.");
console.log("I dont give a shit about your kids.");
console.log("figure it out.");
